name: Deploy Monitoring Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'monitoring/**'

jobs:
  # ... (lint-and-test job for monitoring/src/*.py as before) ...

  deploy-to-staging:
    name: Deploy Monitoring Infra to Staging
    runs-on: ubuntu-latest
    needs: lint-and-test
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      # ... (checkout, configure AWS creds, setup Terraform) ...
      - name: Terraform Apply Monitoring
        run: |
          cd monitoring/infra
          terraform init
          terraform apply -auto-approve -var="env=staging"
  
  run-integration-test:
    name: Run Monitoring Integration Test
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    environment: staging
    steps:
      # ... (setup, configure AWS creds, install dependencies) ...
      - name: Run E2E Monitoring Test
        env:
          STAGING_API_ENDPOINT: ${{ secrets.STAGING_API_ENDPOINT }}
          STAGING_LOG_BUCKET: "rag-log-archive-staging" # This could also be a secret or TF output
        run: pytest monitoring/tests/integration/